# Generated by Django 5.2.3 on 2025-07-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('image', models.ImageField(blank=True, upload_to='doctor_images/')),
            ],
        ),
    ]
