from django.shortcuts import render

# A dictionary of 100+ symptoms with basic suggested medicines
symptom_responses = {
    "fever": "Take paracetamol (e.g., Calpol, Panadol). Stay hydrated.",
    "cough": "Try a cough syrup like Benadryl or take honey with warm water.",
    "sore throat": "Use throat lozenges or take warm salt water gargles.",
    "runny nose": "Use antihistamines like Cetirizine.",
    "sneezing": "Try an antihistamine like Loratadine.",
    "headache": "You can take paracetamol or ibuprofen.",
    "nausea": "Try anti-nausea meds like Ondansetron or drink ginger tea.",
    "vomiting": "Use antiemetics like Domperidone or Ondansetron.",
    "diarrhea": "Take ORS and medicines like Loperamide.",
    "fatigue": "Get rest and consider taking multivitamins.",
    "muscle pain": "Use pain relievers like ibuprofen or apply muscle relaxants.",
    "joint pain": "NSAIDs like ibuprofen or topical gels like Volini may help.",
    "back pain": "Take rest, apply heat packs, and use pain relievers.",
    "chest pain": "If persistent, seek emergency care. May need aspirin.",
    "abdominal pain": "Try Buscopan for cramps. Avoid spicy food.",
    "dizziness": "Rest and drink water. Try Meclizine if persistent.",
    "shortness of breath": "Use inhalers (e.g., Salbutamol) if asthmatic. Seek help if severe.",
    "wheezing": "Use bronchodilators like salbutamol inhaler.",
    "rash": "Use antihistamines or calamine lotion.",
    "itching": "Try antihistamines like Cetirizine.",
    "chills": "Wrap up warmly and monitor for fever.",
    "sweating": "Monitor if with fever. Stay cool.",
    "loss of appetite": "Try small frequent meals. Vitamin B-complex may help.",
    "weight loss": "Consult doctor if unintentional. Try nutritional supplements.",
    "weight gain": "Avoid sugary food. Check thyroid levels.",
    "blurred vision": "Use lubricating eye drops or consult eye specialist.",
    "red eyes": "Use anti-inflammatory eye drops (e.g., Refresh Tears).",
    "dry eyes": "Use artificial tear drops like Systane.",
    "eye pain": "Use cold compress. See a doctor if persistent.",
    "earache": "Try warm compress and ear drops like Otipax.",
    "hearing loss": "Temporary? Try cleaning ears. Else, consult ENT.",
    "ringing in ears": "Avoid loud sounds. Consult doctor.",
    "nasal congestion": "Use saline nasal spray or steam inhalation.",
    "toothache": "Use painkillers and apply clove oil. See a dentist.",
    "mouth ulcers": "Use topical gels like Bonjela.",
    "dry mouth": "Chew sugar-free gum and stay hydrated.",
    "sensitivity to light": "Use sunglasses and rest eyes.",
    "sensitivity to sound": "Avoid noise, rest. Seek advice if continues.",
    "palpitations": "Take deep breaths. Avoid caffeine. Seek help if frequent.",
    "high blood pressure": "Use prescribed antihypertensives like Amlodipine.",
    "low blood pressure": "Drink more fluids, add salt. Lie down if dizzy.",
    "frequent urination": "Could be UTI or diabetes. Drink water. Consult doctor.",
    "painful urination": "Likely UTI. Use antibiotics like Nitrofurantoin (consult doctor).",
    "blood in urine": "Seek medical help immediately.",
    "constipation": "Use stool softeners like Lactulose or drink more water.",
    "bloating": "Try simethicone drops or drink ginger tea.",
    "gas": "Use antacids or simethicone tablets.",
    "heartburn": "Use antacids like Gelusil or proton pump inhibitors like Omeprazole.",
    "difficulty swallowing": "Drink warm liquids. See doctor if persists.",
    "hiccups": "Hold your breath or sip cold water.",
    "anxiety": "Try deep breathing. Mild cases may benefit from herbal teas or Ashwagandha.",
    "depression": "Talk to someone. Consider vitamin D or St. John's Wort (if not on other meds).",
    "insomnia": "Avoid caffeine. Try melatonin supplements.",
    "excessive sleepiness": "Could be fatigue. Try vitamin B12.",
    "irritability": "Relaxation techniques and magnesium supplements may help.",
    "memory loss": "Try Ginkgo Biloba or brain games.",
    "confusion": "Seek immediate medical attention if sudden.",
    "hallucinations": "Consult psychiatrist or neurologist immediately.",
    "tremors": "Try reducing caffeine. May need neurology consult.",
    "numbness": "Could be nerve issue. Take B12 supplements.",
    "tingling": "Common in vitamin B deficiencies. Try supplements.",
    "cold hands": "Warm up and check circulation.",
    "cold feet": "Wear warm socks. Check for circulation issues.",
    "hot flashes": "Use cool packs. May be hormonal (esp. in menopause).",
    "night sweats": "Wear breathable clothes. Monitor if persistent.",
    "bruising easily": "Could be vitamin K deficiency. Eat leafy greens.",
    "bleeding gums": "Use vitamin C and brush gently.",
    "nosebleeds": "Pinch nose, lean forward. Use nasal sprays.",
    "swollen lymph nodes": "May be infection. Take warm compress.",
    "yellowing of skin": "Could be jaundice. Consult doctor.",
    "yellowing of eyes": "May indicate liver issues. Seek advice.",
    "dark urine": "Drink more water. Monitor for liver/kidney issues.",
    "light-colored stools": "May be liver related. Monitor symptoms.",
    "itchy scalp": "Use anti-dandruff shampoos like Nizoral.",
    "hair loss": "Try biotin supplements or minoxidil.",
    "brittle nails": "Use biotin and moisturize often.",
    "skin peeling": "Moisturize regularly. Use aloe vera gel.",
    "acne": "Use benzoyl peroxide or salicylic acid.",
    "eczema": "Apply moisturizers and hydrocortisone cream.",
    "psoriasis": "Use coal tar or salicylic acid cream.",
    "hives": "Take antihistamines and avoid triggers.",
    "cramps": "Stretch and take magnesium/calcium supplements.",
    "menstrual irregularities": "Try hormonal therapy after consultation.",
    "breast pain": "Apply cold compress or use pain relievers.",
    "lump in breast": "Seek medical advice urgently.",
    "erectile dysfunction": "Consult doctor. Sildenafil may help.",
    "low libido": "Can try zinc, ashwagandha. Avoid stress.",
    "pain during intercourse": "Use lubricants. Seek gynecological help.",
    "infertility": "Requires tests. Start with folic acid supplements.",
    "swollen joints": "Apply ice and take NSAIDs.",
    "stiffness": "Stretch daily. Try warm compresses.",
    "difficulty walking": "May need physiotherapy.",
    "slurred speech": "Could be serious. Seek urgent care.",
    "seizures": "Ensure safety. Use antiepileptics if diagnosed.",
    "loss of balance": "Can be inner ear or neuro. Do balance exercises.",
    "difficulty concentrating": "Try omega-3 or avoid distractions.",
    "frequent infections": "Boost immunity with vitamin C and zinc.",
    "cold-like symptoms": "Rest, fluids, paracetamol for fever.",
    "general malaise": "Rest, hydration, multivitamins.",
    "swelling in legs": "Elevate legs, reduce salt. May need diuretics."
}

def chatbot_view(request):
    response = ""
    if request.method == "POST":
        symptoms = request.POST.get("symptoms", "").lower()
        found = False
        for symptom in symptom_responses:
            if symptom in symptoms:
                response += f"{symptom.title()}: {symptom_responses[symptom]}<br>"
                found = True
        if not found:
            response = "Sorry, I don't have a recommendation for these symptoms yet."
    return render(request, "chatbot/chatbot.html", {"response": response})
